### ISSUE TITLE
django.db.utils.OperationalError: no such table: users_user

### ISSUE THREAD

**Issue by crasybest** [itnotebooks/cert_manage#1]
执行python run_server.py后，抛异常：
- Start Gunicorn WSGI HTTP Server
Check database structure change...
Operations to perform:
  Apply all migrations: admin, auth, captcha, contenttypes, django_celery_beat, sessions
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: users_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cms", line 333, in <module>
    start_service(srv)
  File "cms", line 234, in start_service
    p = func()
  File "cms", line 135, in start_gunicorn
    prepare()
  File "cms", line 72, in prepare
    make_superuser()
  File "cms", line 60, in make_superuser
    if not User.objects.filter(username='admin'):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 278, in __bool__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: users_user

使用的是sqlite3

**Comment by ericwinn** [comment]
代码更新了，你获取下最新的代码，然后卸载掉Django2.2，安装2.1.11，再执行启动命令就可以了

**Comment by crasybest** [comment]
已经可以了，多谢

**Comment by crasybest** [comment]
已解决！
